# Generated by Django 4.2.13 on 2024-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="نام"),
                ),
                (
                    "persian_name",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="نام فارسی"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("boy", "Boy"), ("girl", "Girl")],
                        max_length=120,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="کشور"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="ملیت"
                    ),
                ),
                (
                    "Usage_percentage",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="استفاده"
                    ),
                ),
                (
                    "pronunciation",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="تلفط"
                    ),
                ),
                (
                    "meaning",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="معنی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
            ],
            options={
                "verbose_name": "نام",
                "verbose_name_plural": "اسامی",
                "ordering": ["-created_at"],
            },
        ),
    ]
