# Generated by Django 4.2.13 on 2024-07-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("names", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="desteni_number",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="عدد تقدیر"
            ),
        ),
        migrations.AddField(
            model_name="name",
            name="motivation_number",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="عدد روح"
            ),
        ),
    ]
