# Generated by Django 4.2.13 on 2024-07-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("names", "0002_name_desteni_number_name_motivation_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="name",
            options={"verbose_name": "نام", "verbose_name_plural": "اسامی"},
        ),
    ]
