# Generated by Django 5.0.4 on 2024-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="reinforcement",
            field=models.ManyToManyField(
                blank=True, null=True, to="chart.zodiac", verbose_name="تقویت"
            ),
        ),
    ]
