# Generated by Django 5.0.4 on 2024-04-25 08:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0002_alter_plant_reinforcement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="psychology",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "نکته روانشناسی",
                "verbose_name_plural": "نکات روانشناسی",
            },
        ),
        migrations.AlterField(
            model_name="detail",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="plantlayer",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="psychology",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="zodiac",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="توضیحات"
            ),
        ),
    ]
