# Generated by Django 5.0.4 on 2024-04-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0003_alter_psychology_options_alter_detail_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="name",
        ),
    ]
