# Generated by Django 5.0.4 on 2024-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0004_remove_detail_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="name",
            field=models.CharField(default=1, max_length=120, verbose_name="نام فارسی"),
            preserve_default=False,
        ),
    ]
