# Generated by Django 5.0.4 on 2024-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0005_detail_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="name",
            field=models.CharField(max_length=120, null=True, verbose_name="نام"),
        ),
    ]
